<?php

namespace AppBundle\Repository;

/**
 * MbDurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbDurationRepository extends \Doctrine\ORM\EntityRepository
{
}
