<?php

namespace AppBundle\Repository;

/**
 * MbOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
