<?php

namespace AppBundle\Repository;

/**
 * MbPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
