<?php

namespace AppBundle\Repository;

/**
 * MbTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
