<?php

namespace AppBundle\Repository;

/**
 * MbTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbTagRepository extends \Doctrine\ORM\EntityRepository
{
}
