<?php

namespace AppBundle\Repository;

/**
 * MbTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
