<?php

namespace AppBundle\Repository;

/**
 * MbTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbTicketRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTicketsByDate($date)
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$query = $qb->select('t')
            ->from('AppBundle:MbTicket', 't')
            ->where('t.date = :date')
            ->setParameter('date', $date->format('Y-m-d'))
            ->getQuery();

		return $query->getResult();
	}


	public function getTicketNbByDate($date)
	{
		// Remplacer par une requête qui compte les éléments mais qui ne les récupère pas
		return count(SELF::findAllTicketsByDate($date));
	}
}
