<?php

namespace AppBundle\Repository;

/**
 * MbUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbUserRepository extends \Doctrine\ORM\EntityRepository
{
}
